title: Home <br> 
logo: /images/LinkedinPic.png
description: Do a quick about me here
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
relative_links:
  enabled:     true
  collections: false
highlighter: rouge
markdown: kramdown
kramdown:
  parse_block_html: true
